# Generated by Django 2.2.1 on 2020-05-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='course_id')),
                ('course_title', models.CharField(max_length=480, verbose_name='course_title')),
                ('url', models.CharField(max_length=480, verbose_name='url')),
                ('is_paid', models.BooleanField(max_length=480, verbose_name='is_paid')),
                ('price', models.IntegerField(verbose_name='price')),
                ('num_subscribers', models.IntegerField(verbose_name='num_subscribers')),
                ('num_reviews', models.IntegerField(verbose_name='num_reviews')),
                ('num_lectures', models.IntegerField(verbose_name='num_lectures')),
                ('level', models.CharField(max_length=480, verbose_name='level')),
                ('content_duration', models.CharField(max_length=255, verbose_name='content_duration')),
                ('published_timestamp', models.DateField(verbose_name='published_timestamp')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
            ],
        ),
    ]
