# Generated by Django 2.2.1 on 2020-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_timestamp',
            field=models.DateTimeField(verbose_name='published_timestamp'),
        ),
    ]
